### ISSUE TITLE
Geometry - OGR_G_GetEnvelope crashes

### ISSUE THREAD

**Issue by shawnlaffan** [ajolma/Geo-GDAL-FFI#19]
Calling OGR_G_GetEnvelope on a Geometry object results in a crash.  See code below.  

The FFI bindings are set as ```'OGR_G_GetEnvelope' => [qw/opaque double[4]/] => 'void');```, but if I am reading the GDAL header files correctly then it needs to be passed an Envelope struct and not an array ref?

The SWIG bindings don't seem to help in this regard as they call ```$self->GetEnvelope``` but I cannot see where it originates from.  

```
use 5.010;
use Geo::GDAL::FFI;


say 'Generating polygon';

my $filt_poly = Geo::GDAL::FFI::Geometry->new(
    WKT => 'POLYGON ((4 0, 4 4, 0 4, 0 0, 4 0))',
);

say 'WKT:';
say $filt_poly->ExportToJSON;
#  next line purely for debug
my $ptlist = $filt_poly->GetPoints;

say 'Getting envelope';
my $envelope = [0,0,0,0];
Geo::GDAL::FFI::OGR_G_GetEnvelope ($filt_poly, $envelope);

say 'Envelope is ' . join ' ', @$envelope;
say 'got to end';

```

**Comment by ajolma** [comment]
Should be
```
Geo::GDAL::FFI::OGR_G_GetEnvelope ($$filt_poly, $envelope);
```
and then it seems to work.
OGREnvelope is hard coded to double[4] in build-tools/parse_h.pl as it is a struct of four doubles.

**Comment by shawnlaffan** [comment]
Thanks Ari.  

I should have remembered that since all the other methods dereference the caller.  

I'll close this issue and work up a PR.
