### ISSUE TITLE
Error handler conflates fatal and warning level errors

### ISSUE THREAD

**Issue by shawnlaffan** [ajolma/Geo-GDAL-FFI#33]
The error handling code in Geo::GDAL::FFI appears to conflate both warning and fatal level errors.  

This can cause action at a distance issues where one operation logs warnings into ```@Geo::GDAL::FFI::errors```.  When a later unrelated method call encounters a fatal error (or checks if ```@Geo::GDAL::FFI::errors``` has any contents) then it throws an exception, listing the warning before the error.  

One example of this is the Layer Intersection method, which logs warnings when multipart polygons are loaded into a geopackage that expects simple polygons (related to https://trac.osgeo.org/gdal/ticket/4939 ).  If a (much) later function checks for errors then it calls confess to report the Intersection warnings.  

Perhaps the error handler should log any warnings to STDERR, and not push them onto ```@Geo::GDAL::FFI::errors``` .  

I'd work up a PR, but I'm not sure how to check for error level given the arguments passed to the error handler.

**Comment by ajolma** [comment]
Fixed in f0245f9
