### ISSUE TITLE
GetCategoryNames method?

### ISSUE THREAD

**Issue by shawnlaffan** [ajolma/Geo-GDAL-FFI#4]
I'm porting my code across to Geo::GDAL::FFI from Geo::GDAL, and cannot find a method in the code for Geo::GDAL::Band::CategoryNames.

There seems to be something in the code, but I am unsure which object type it applies to.  

https://github.com/ajolma/Geo-GDAL-FFI/blob/24300784d59fe5ecf46b2e60f5a8fe5741e71b35/lib/Geo/GDAL/FFI.pm#L505-L506

**Comment by ajolma** [comment]
It is not yet implemented as a method in the class. It could be used for a band object but I'm afraid the parameter should be opaque instead of string_pointer (the function should be added to parse_h.pl) since it is a string list.

**Comment by shawnlaffan** [comment]
OK, I'll skip category names for now.
