### ISSUE TITLE
FFI::Platypus::Declare is now a separate distribution, needs to be added to Makefile.PL

### ISSUE THREAD

**Issue by shawnlaffan** [ajolma/Geo-GDAL-FFI#40]
FFI::Platypus::Declare has recently been released as a stand-alone distribution, so Geo::GDAL::FFI now fails to build on a clean system.

https://metacpan.org/release/FFI-Platypus-Declare

It is also now discouraged, but that warrants its own issue.  

I can provide a PR, but it should just be a one line change.

**Comment by ajolma** [comment]
Fixed in https://github.com/ajolma/Geo-GDAL-FFI/commit/aeedff859bca0eadfe274776f7733c885be97e4b
