### ISSUE TITLE
Drive by comment: consider ignore_not_found

### ISSUE THREAD

**Issue by plicease** [ajolma/Geo-GDAL-FFI#42]
This is just a drive by suggestion peeking at the source code of this module you have a lot of attach calls wrapped in evals that ignore the exception, if thrown:

https://github.com/ajolma/Geo-GDAL-FFI/blob/master/lib/Geo/GDAL/FFI.pm#L448

This is exactly the use case intended by the ignore_not_found attribute:

https://metacpan.org/pod/FFI::Platypus#ignore_not_found1

which would save an eval and make the code a little shorter :)

You can even turn it on and off if you need to:

```perl
$ffi->ignore_not_found(1);
$ffi->attach( optional_func => ... );
$ffi->ignore_not_found(0);
$ffi->attach( required_func => ... );
```

**Comment by ajolma** [comment]
https://github.com/ajolma/Geo-GDAL-FFI/commit/4741fa1a3642ba325fe24671a35269d969bc934e
a bit late, but done now
