### ISSUE TITLE
Add recent OGRGeometry functions

### ISSUE THREAD

**Issue by shawnlaffan** [ajolma/Geo-GDAL-FFI#44]
There are a few recent additions to OGRGeometry that would be useful to have.  They will need to be version guarded but that should not be too complex?

MakeValid (since GDAL 3.0)
https://gdal.org/doxygen/classOGRGeometry.html#a700a2d4b1c719e1f65fa3009bfc04f78

Normalize (since GDAL 3.3)
https://gdal.org/doxygen/classOGRGeometry.html#aa518a2cafc2a2394bc3a5196fa7dd017

There are others for which there seem to be bindings but no methods, e.g. Polygonize.

**Comment by ajolma** [comment]
I updated the bindings and added MakeValid. Seems that travis.org is not available any more, so how to switch to travis.com?

**Comment by shawnlaffan** [comment]
Thanks.  

We can switch to github actions.  I have some examples in https://github.com/shawnlaffan/geo-gdal-ffi-canary/tree/master/.github/workflows

There is also Cirrus which will provides a FreeBSD CI.  https://github.com/shawnlaffan/geo-gdal-ffi-canary/blob/master/.cirrus.yml

**Comment by shawnlaffan** [comment]
Those examples have several elements not needed for this repo.  I'll set up some PRs.

**Comment by ajolma** [comment]
What do you mean by "version guarded"? The method should check the version and fail if it is not ok?

**Comment by shawnlaffan** [comment]
Yes, that's what I mean.

**Comment by shawnlaffan** [comment]
Normalize was added in b804ef39483e89cfcf45082425e69dcd12cf10da so this issue is closable.
