### ISSUE TITLE
How to do coordinate transformations in Geo::GDAL::FFI

### ISSUE THREAD

**Issue by yelnats** [ajolma/Geo-GDAL-FFI#47]
How are coordinate transformations done in Geo::GDAL::FFI?

In the old perl bindings it was Geo::OSR::CoordinateTransformation

Something like:

use Geo::GDAL::FFI;
my $srs_from  = Geo::GDAL::FFI::SpatialReference->new(EPSG => 4326);
my $srs_to      = Geo::GDAL::FFI::SpatialReference->new(EPSG => 3067);
$transf = new Geo::GDAL::FFI::CoordinateTransformation($srs_from, $srs_to);

**Comment by yelnats** [comment]
I see, I can use ('OCTNewCoordinateTransformation' => [qw/opaque opaque/] => 'opaque');};

**Comment by ajolma** [comment]
Yes, there is a binding for that function but no class defined yet.
