### ISSUE TITLE
Should Geo::GDAL::FFI::Band inherit from Geo::GDAL::FFI::Object?

### ISSUE THREAD

**Issue by shawnlaffan** [ajolma/Geo-GDAL-FFI#50]
It seems that Geo::GDAL::FFI::Band does not inherit from Geo::GDAL::FFI::Object, but perhaps it should?  

It seems it did under the old system.
https://arijolma.org/Geo-GDAL/2.4/classGeo_1_1GDAL_1_1Band.html

**Comment by ajolma** [comment]
It seems to do no harm and set/get metadata to/from band seems to work.
[https://github.com/ajolma/Geo-GDAL-FFI/commit/1ff3c70ea637a3e8117a66b962764e884a4dc332](url)
