### ISSUE TITLE
warning received during loading $FFI::Platypus 'used only once'

### ISSUE THREAD

**Issue by yelnats** [ajolma/Geo-GDAL-FFI#52]
Had to define,

{						
   local $FFI::Platypus::keep;
   local $FFI::Platypus::TypeParser::ffi_type; }
}

Or I get a warning during loading that it was used only once.

Name "FFI::Platypus::keep" used only once: possible typo at /usr/lib/x86_64-linux-gnu/perl-base/XSLoader.pm
Name "FFI::Platypus::TypeParser::ffi_type" used only once: possible typo at /usr/lib/x86_64-linux-gnu/perl-base/XSLoader.pm

**Comment by shawnlaffan** [comment]
I have similar code in my own code to suppress such warnings from the past.  However, disabling them does not make the issue reappear now.  

I can only reproduce it locally if I run with global warnings enabled.  

```
perl -MGeo::GDAL::FFI -W -E' my $g = Geo::GDAL::FFI->new'
```

That said, it does not hurt to add the block.
