### ISSUE TITLE
JSON::PP::Boolean redefined warnings

### ISSUE THREAD

**Issue by shawnlaffan** [ajolma/Geo-GDAL-FFI#6]
The first code block produces redefined warnings.  The second does not.  

There seems to be something in one of the dependencies that is triggering it, but I have not been able to track it down yet.  

```
use 5.010;
use strict;
use warnings;

use JSON::MaybeXS;
use Geo::GDAL::FFI;
```

```
Subroutine JSON::PP::Boolean::(++ redefined at C:/berrybrew/5.26.1_64_PDL/perl/lib/overload.pm line 48.
Subroutine JSON::PP::Boolean::(0+ redefined at C:/berrybrew/5.26.1_64_PDL/perl/lib/overload.pm line 48.
Subroutine JSON::PP::Boolean::(-- redefined at C:/berrybrew/5.26.1_64_PDL/perl/lib/overload.pm line 48.
```

```
use 5.010;
use strict;
use warnings;

use Geo::GDAL::FFI;
use JSON::MaybeXS;
```

**Comment by ajolma** [comment]
Not in my machine. I have PDL 2.018, JSON::MaybeXS 1.003009 and Perl 5.26.0. Anyway IMO it's something between JSON and PDL.

**Comment by shawnlaffan** [comment]
Thanks. I figured it was a dependency somewhere, as there are no explicit calls to a perl JSON package in the Geo::GDAL::FFI code.  

I can't reproduce it using PDL instead of Geo::GDAL::FFI, so I need to look further.  

Just for the record, I'm on Windows 10 and have
PDL 2.018
JSON::MaybeXS 1.004
JSON::XS 3.04
Cpanel-JSON-XS 4.06 (was 3.023)

**Comment by shawnlaffan** [comment]
I installed the latest version from github and now I cannot reproduce it using the script above, even when reverting to the version on metacpan.  I still get the warnings when I run the Biodiverse test suite, though.
