### ISSUE TITLE
Add Layer methods for Intersection, Union etc

### ISSUE THREAD

**Issue by shawnlaffan** [ajolma/Geo-GDAL-FFI#7]
It seems the Intersection, Union and similar methods are not yet implemented for layers.  

e.g. https://www.gdal.org/classOGRLayer.html#a5202606175f7e7dcd76c3eb237ac8303

I can use geometry objects to achieve the same results, but it would avoid some looping if it could be applied at the Layer level.

**Comment by ajolma** [comment]
Added in 04a29b4

**Comment by shawnlaffan** [comment]
Thanks Ari.

**Comment by shawnlaffan** [comment]
I get test failures in layer.t, presumably because my GDAL was not built with GEOS, but possibly for other reasons.   

Wrapping the Intersection call in an eval and printing the error, I get the text below.  Geo::GDAL::FFI::error_msg() seems to be empty.

```
[
  "Unknown error at C:\\git\\Geo-GDAL-FFI\\blib\\lib/Geo/GDAL/FFI/Layer.pm line 122.\n\tGeo::GDAL::FFI::Layer::Intersection(Geo::GDAL::FFI::Layer=SCALAR(0x446cf58), Geo::GDAL::FFI::Layer=SCALAR(0x54bb4a0), HASH(0x54bbc68)) called at t\\layer.t line 42\n\teval {...} called at t\\layer.t line 41\n",
]
# 1
not ok 1 - Intersection progress.
#   Failed test 'Intersection progress.'
#   at t\layer.t line 48.
Can't call method "ResetReading" on an undefined value at t\layer.t line 68.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 1 just after 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

**Comment by ajolma** [comment]
The 'Unknown error' is because of a typo in the method code, should be 'OGRError'. Fixed that.
Also skip now layer.t tests if no GEOS. c7c177e
