### ISSUE TITLE
Document Geo::GDAL::FFI::error_msg

### ISSUE THREAD

**Issue by shawnlaffan** [ajolma/Geo-GDAL-FFI#8]
I can provide a pull request for this one if you provide some pointers.

**Comment by ajolma** [comment]
It is meant to be an internal method and called in methods when there was an error in a GDAL function (the function returns an error code or nothing when it was supposed to return something). 

It attempts to create a unified (internal) API for spitting out a sensible error message. The message is composed from a) internal error stack that is filled by CPLErrorHandler which is installed and then called by GDAL for all errors - GDAL may call it many times before it returns from an API function, or b) textualized OGRError code, or c) "Unknown error" when the argument is not understood.

Call it without an argument or with a ref to hash which has key OGRError with OGR error code (integer 1..9) as the value.

**Comment by ajolma** [comment]
Maybe the two cases should be combined, i.e., maybe(?) OGR function returns an error code but it has also called the error handler before returning.

**Comment by shawnlaffan** [comment]
Thanks.  

The system might need a more generic error reporting system so the GDAL errors are exposed.  

If I run code like this:

```perl
$geom->Intersection ($fish->GetGeomField);
```

then it dies with the exception:
```
Modification of a read-only value attempted at C:/berrybrew/5.28.0_64_PDL/perl/site/lib/Geo/GDAL/FFI/Geometry.pm line 262.
```

When I wrap it in an eval 

```perl
my $intersection = eval {
    $geom->Intersection ($fish->GetGeomField);
};
warn Geo::GDAL::FFI::error_msg() if $@;
```

I get the error:

```
GEOS support not enabled. at C:\shawn\git\biodiverse\etc\experiments\polygon_intersect.pl line 29.
```

Getting GEOS support to work is relatively straightforward (see shawnlaffan/perl-alien-geos), except on Windows due to makefile command lengths (but that's a different issue).

**Comment by shawnlaffan** [comment]
And by "exposed" I mean through the usual perl channels like warning.

**Comment by ajolma** [comment]
I've done a minimal job in wrapping those methods. Also for example
```
$g->Intersection(undef);
```
dumps core since GDAL does not validate the pointer. (I think it should).
Perhaps something like this would be ok:
```
sub Intersection {
    my ($self, $geom) = @_;
    confess "Undefined geometry." unless $geom;
    $self = Geo::GDAL::FFI::OGR_G_Intersection($$self, $$geom);
    confess Geo::GDAL::FFI::error_msg() unless $self;
    return bless \$self, 'Geo::GDAL::FFI::Geometry';
}
```

**Comment by shawnlaffan** [comment]
Something along those lines would be good, I think.

**Comment by ajolma** [comment]
Done in c7c177e.

**Comment by shawnlaffan** [comment]
Thanks again.
